import type { StyleConfig } from '../../types/project';

export const EDITORIAL_BURGUNDY: StyleConfig = {
  presetName: 'Editorial Burgundy',
  primaryBg: '#3F0707',
  secondaryBg: '#F3E8D5',
  primaryTextColor: '#F5E4C4',
  secondaryTextColor: '#3F0707',
  accentColor: '#936B53',
  fontFamily: 'Playfair Display',
  fontSizeRatio: 1.0,
  lineHeight: 1.18,
  letterSpacing: -0.5,
  textAlign: 'center',
  grainIntensity: 0.22,
  vignetteIntensity: 0.32,
  alternatingScenes: true,
  showStarDecoration: true,
  maxLinesOnScreen: 2,
};

export const CREAM_EDITORIAL: StyleConfig = {
  presetName: 'Cream Editorial',
  primaryBg: '#F5ECE0',
  secondaryBg: '#3B0909',
  primaryTextColor: '#3B0909',
  secondaryTextColor: '#F5ECE0',
  accentColor: '#8E6349',
  fontFamily: 'DM Serif Display',
  fontSizeRatio: 1.0,
  lineHeight: 1.15,
  letterSpacing: -0.5,
  textAlign: 'center',
  grainIntensity: 0.16,
  vignetteIntensity: 0.18,
  alternatingScenes: false,
  showStarDecoration: true,
  maxLinesOnScreen: 2,
};

export const MIDNIGHT_VINTAGE: StyleConfig = {
  presetName: 'Midnight Vintage',
  primaryBg: '#181413',
  secondaryBg: '#E9E0CF',
  primaryTextColor: '#ECE3D1',
  secondaryTextColor: '#181413',
  accentColor: '#A88B70',
  fontFamily: 'Cormorant Garamond',
  fontSizeRatio: 1.1,
  lineHeight: 1.15,
  letterSpacing: 0,
  textAlign: 'center',
  grainIntensity: 0.25,
  vignetteIntensity: 0.42,
  alternatingScenes: false,
  showStarDecoration: true,
  maxLinesOnScreen: 2,
};

export const DEEP_FOREST: StyleConfig = {
  presetName: 'Deep Forest',
  primaryBg: '#18442A',
  secondaryBg: '#45644A',
  primaryTextColor: '#F3EDE3',
  secondaryTextColor: '#18442A',
  accentColor: '#E4DBC4',
  fontFamily: 'Cormorant Garamond',
  fontSizeRatio: 1.05,
  lineHeight: 1.15,
  letterSpacing: -0.3,
  textAlign: 'center',
  grainIntensity: 0.18,
  vignetteIntensity: 0.28,
  alternatingScenes: true,
  showStarDecoration: true,
  maxLinesOnScreen: 2,
};

export const OLIVE_EDITORIAL: StyleConfig = {
  presetName: 'Olive Editorial',
  primaryBg: '#45644A',
  secondaryBg: '#18442A',
  primaryTextColor: '#F3EDE3',
  secondaryTextColor: '#E4DBC4',
  accentColor: '#E4DBC4',
  fontFamily: 'DM Serif Display',
  fontSizeRatio: 1.0,
  lineHeight: 1.15,
  letterSpacing: -0.4,
  textAlign: 'center',
  grainIntensity: 0.16,
  vignetteIntensity: 0.22,
  alternatingScenes: true,
  showStarDecoration: true,
  maxLinesOnScreen: 2,
};

export const SAND_PAPER: StyleConfig = {
  presetName: 'Sand Paper',
  primaryBg: '#E4DBC4',
  secondaryBg: '#F3EDE3',
  primaryTextColor: '#18442A',
  secondaryTextColor: '#45644A',
  accentColor: '#45644A',
  fontFamily: 'Playfair Display',
  fontSizeRatio: 1.0,
  lineHeight: 1.18,
  letterSpacing: -0.2,
  textAlign: 'center',
  grainIntensity: 0.22,
  vignetteIntensity: 0.15,
  alternatingScenes: false,
  showStarDecoration: true,
  maxLinesOnScreen: 2,
};

export const OFF_WHITE_EDITORIAL: StyleConfig = {
  presetName: 'Off White Editorial',
  primaryBg: '#F3EDE3',
  secondaryBg: '#E4DBC4',
  primaryTextColor: '#18442A',
  secondaryTextColor: '#45644A',
  accentColor: '#45644A',
  fontFamily: 'Cormorant Garamond',
  fontSizeRatio: 1.1,
  lineHeight: 1.15,
  letterSpacing: -0.3,
  textAlign: 'center',
  grainIntensity: 0.14,
  vignetteIntensity: 0.12,
  alternatingScenes: false,
  showStarDecoration: true,
  maxLinesOnScreen: 2,
};

export const STYLE_PRESETS: Record<string, StyleConfig> = {
  'Deep Forest': DEEP_FOREST,
  'Olive Editorial': OLIVE_EDITORIAL,
  'Sand Paper': SAND_PAPER,
  'Off White Editorial': OFF_WHITE_EDITORIAL,
  'Editorial Burgundy': EDITORIAL_BURGUNDY,
  'Cream Editorial': CREAM_EDITORIAL,
  'Midnight Vintage': MIDNIGHT_VINTAGE,
};
